### PR TITLE
Fix edit-markup replacement

### LINKED ISSUE #12: Clicking on suggestions inserts the message
Even though some edits just remove text, we still need to display some text the users can click on, but it's not always intended that that text gets replaced (e.g. by clicking on "Remove sledgehammer", the command "sledgehammer" should be removed, not replaced with "Remove sledgehammer").

An easy fix, probably something went wrong during the integration

### PR DESCRIPTION
**Pull request by TheMC47**
closes #12

### CODE REVIEW

File: jedit_linter/src/jedit_extension.scala [hunk 1]
```diff
@@ -56,7 +56,7 @@ object JEdit_Extension
     range: Symbol.Range, text: String): Unit =
   {
     val buffer = text_area.getBuffer
-    if (!snapshot.is_outdated && text != "") {
```
Comment (Dacit) [inline jedit_linter/src/jedit_extension.scala:59]: What is this check for?

Comment (Dacit) [reply jedit_linter/src/jedit_extension.scala:59]: Oh, that was removed.
